#!/bin/bash

GTK_PID=$(pgrep gtkwave)
if [ ! -z "{$GTK_PID}" ]
then
	echo "Killing gtkwave"
	kill $GTK_PID
fi

# exists when command fails
set -e

echo "Verifying vhd syntax"
#ghdl -s *.vhd
#ghdl -s simple_risc_def.vhd
#ghdl -s simple_risc_programs.vhd
#ghdl -s simple_risc_mem_if.vhd
#ghdl -s simple_risc_cu.vhd
#ghdl -s simple_risc.vhd
#ghdl -s simple_risc_tb.vhd

echo "Analysing vhdl"
#ghdl -a *.vhd
ghdl -a simple_risc_def.vhd
ghdl -a simple_risc_programs.vhd
ghdl -a simple_risc_mem_if.vhd
ghdl -a simple_risc_cu.vhd
ghdl -a simple_risc.vhd
ghdl -a simple_risc_tb.vhd

echo "Compiling vhdl testbench"
ghdl -e simple_risc_tb


echo "Elaborating testbench UNIT"
ghdl -e simple_risc_tb

echo "Running simulation"
ghdl -r simple_risc_tb --wave=new.ghw --stop-time=1000ns 

echo "Cleaning files"
ghdl --clean
rm *.cf

echo "Opening gtkwave"
gtkwave simulation_wave.gtkw &>/dev/null &
echo "Done"
